//! The egui application: toolbar, page list and the pan/zoom canvas.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, mpsc};
use std::time::Instant;

use eframe::egui::{
    self, Align, Color32, FontData, FontDefinitions, FontFamily, FontId, Key, Mesh, Pos2, Rect, Sense,
    Shape, Stroke, TextFormat, TextureHandle, TextureOptions, Vec2, ViewportCommand, epaint,
    text::LayoutJob,
};

use crate::find::Find;
use vera_view::model::{Document, Page};
use vera_view::scene::{self, ItemKind, Scene, TextItem};

/// 100% zoom means one paper inch is 96 screen points.
const POINTS_PER_INCH: f32 = 96.0;
const MIN_ZOOM: f32 = 1.0;
const MAX_ZOOM: f32 = 20_000.0;
/// Largest font size we ask egui to rasterise.
const MAX_FONT_PX: f32 = 400.0;

const EXTENSIONS: &[&str] = &["vsdx", "vsdm", "vstx", "vstm", "vsd"];

#[derive(Default)]
pub struct Args {
    pub file: Option<PathBuf>,
    pub page: usize,
    /// Render the file, save a screenshot to this path and exit.
    pub screenshot: Option<PathBuf>,
    /// Initial view: paper x, paper y (inches, y up) at the centre, and zoom percent.
    pub view: Option<[f32; 3]>,
    /// Search for this text once the file has loaded.
    pub find: Option<String>,
    /// Show the About box on start.
    pub about: bool,
    /// Show the third-party notices on start.
    pub notices: bool,
}

pub struct ViewerApp {
    doc: Option<Document>,
    path: Option<PathBuf>,
    error: Option<String>,
    page: usize,
    scene: Option<Scene>,
    zoom: f32,
    /// Screen offset of the page's top-left corner from the canvas' top-left.
    pan: Vec2,
    fit_pending: bool,
    show_pages: bool,
    /// Decoded images by package part name; `None` if decoding failed.
    textures: HashMap<String, Option<TextureHandle>>,
    screenshot: Option<PathBuf>,
    frames: u32,
    initial_view: Option<[f32; 3]>,
    /// Time spent building the canvas shapes in the last frame.
    draw_ms: f32,
    /// A file being loaded in the background.
    loading: Option<(PathBuf, mpsc::Receiver<Result<Loaded, String>>)>,
    /// Page to show once the next file has loaded.
    requested_page: usize,
    find: Find,
    /// Search to run once the next file has loaded.
    pending_find: Option<String>,
    /// Incremented whenever `scene` is replaced, so cached matches can be invalidated.
    scene_gen: u64,
    /// Text item to bring into view on the next frame.
    focus_item: Option<usize>,
    /// Where the canvas was last drawn, for keyboard scrolling.
    canvas_rect: Rect,
    show_about: bool,
    about_icon: TextureHandle,
    show_notices: bool,
}

/// Licenses of the open-source components compiled into Vera View, generated by
/// `cargo about` (see installer/build.ps1).
const THIRD_PARTY_NOTICES: &str = include_str!("../THIRD-PARTY-NOTICES.txt");

pub const TRADEMARK_NOTICE: &str = "Microsoft and Visio are trademarks of the Microsoft group of companies.";
pub const INDEPENDENCE_NOTICE: &str = "Vera View is an independent product. It is not affiliated with, sponsored by, \
     or endorsed by Microsoft Corporation.";

/// Thickness of the scroll bars, in points.
const SCROLLBAR: f32 = 12.0;

/// The scrollable range along one axis, in points relative to the canvas.
#[derive(Clone, Copy)]
struct Extent {
    /// Screen offset of the start of the scrollable range (page edge minus margin).
    start: f32,
    /// Length of the scrollable range.
    total: f32,
    /// Length of the visible canvas.
    view: f32,
}

impl Extent {
    /// The `pan` values that keep the view inside the scrollable range.
    fn pan_limits(&self, pan: f32) -> (f32, f32) {
        let margin = pan - self.start;
        (self.view - self.total + margin, margin)
    }
}

struct Loaded {
    doc: Document,
    page: usize,
    scene: Scene,
}

impl ViewerApp {
    pub fn new(cc: &eframe::CreationContext<'_>, args: Args) -> Self {
        install_fonts(&cc.egui_ctx);
        #[cfg(target_os = "macos")]
        crate::macos::set_context(&cc.egui_ctx);
        let mut app = Self {
            doc: None,
            path: None,
            error: None,
            page: 0,
            scene: None,
            zoom: POINTS_PER_INCH,
            pan: Vec2::ZERO,
            fit_pending: true,
            show_pages: true,
            textures: HashMap::new(),
            screenshot: args.screenshot,
            frames: 0,
            initial_view: args.view,
            draw_ms: 0.0,
            loading: None,
            requested_page: 0,
            find: Find::default(),
            pending_find: args.find,
            scene_gen: 0,
            focus_item: None,
            canvas_rect: Rect::NOTHING,
            show_about: args.about,
            show_notices: args.notices,
            about_icon: {
                let icon = crate::window_icon();
                let image = egui::ColorImage::from_rgba_unmultiplied([icon.width as usize, icon.height as usize], &icon.rgba);
                cc.egui_ctx.load_texture("vera-view-icon", image, TextureOptions::LINEAR)
            },
        };
        if let Some(file) = args.file {
            app.requested_page = args.page;
            app.open(&cc.egui_ctx, &file);
        }
        app
    }

    /// Start loading `path` on a background thread; `poll_loading` picks up the result.
    fn open(&mut self, ctx: &egui::Context, path: &Path) {
        let (tx, rx) = mpsc::channel();
        let (path_buf, ctx) = (path.to_path_buf(), ctx.clone());
        let page = std::mem::take(&mut self.requested_page);
        std::thread::spawn(move || {
            let result = Document::open(&path_buf).map(|doc| {
                let page = page.min(doc.pages.len() - 1);
                let scene = scene::build(&doc, page);
                Loaded { doc, page, scene }
            });
            let _ = tx.send(result.map_err(|e| format!("Could not open {}:\n{e:#}", path_buf.display())));
            ctx.request_repaint();
        });
        self.loading = Some((path.to_path_buf(), rx));
    }

    fn poll_loading(&mut self, ctx: &egui::Context) {
        let Some((path, rx)) = &self.loading else { return };
        let result = match rx.try_recv() {
            Ok(result) => result,
            Err(mpsc::TryRecvError::Empty) => return,
            Err(mpsc::TryRecvError::Disconnected) => Err("The loader stopped unexpectedly.".to_string()),
        };
        let path = path.clone();
        self.loading = None;
        match result {
            Ok(Loaded { doc, page, scene }) => {
                self.doc = Some(doc);
                self.scene = Some(scene);
                self.scene_gen += 1;
                self.page = page;
                self.path = Some(path.clone());
                self.error = None;
                self.textures.clear();
                self.fit_pending = true;
                let name = path.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default();
                ctx.send_viewport_cmd(ViewportCommand::Title(format!("{name} - Vera View")));
                if let Some(query) = self.pending_find.take() {
                    self.find.open = true;
                    self.find.query = query;
                    self.find_step(true);
                }
            }
            Err(e) => {
                // Keep showing the previous document, if any; the error goes on top.
                self.error = Some(e);
            }
        }
    }

    fn open_dialog(&mut self, ctx: &egui::Context) {
        let mut dialog = rfd::FileDialog::new().add_filter("Visio drawings", EXTENSIONS);
        if let Some(dir) = self.path.as_deref().and_then(Path::parent) {
            dialog = dialog.set_directory(dir);
        }
        if let Some(path) = dialog.pick_file() {
            self.open(ctx, &path);
        }
    }

    fn set_page(&mut self, page: usize) {
        let Some(doc) = &self.doc else { return };
        let page = page.min(doc.pages.len() - 1);
        if page != self.page {
            self.page = page;
            self.scene = Some(scene::build(doc, page));
            self.scene_gen += 1;
            self.fit_pending = true;
        }
    }

    /// Select the next (or previous) match, moving on to other pages when this
    /// page has no more, and wrapping around at the end of the document.
    fn find_step(&mut self, forward: bool) {
        self.find.message = None;
        self.find.refresh(self.scene.as_ref(), self.scene_gen);
        if !self.find.is_active() {
            return;
        }
        let n = self.find.matches.len();
        let next = match self.find.current {
            Some(c) if forward => (c + 1 < n).then_some(c + 1),
            Some(c) => c.checked_sub(1),
            None if n > 0 => Some(if forward { 0 } else { n - 1 }),
            None => None,
        };
        if let Some(next) = next {
            self.find.current = Some(next);
            self.focus_item = self.find.current_item();
            return;
        }

        // Not on this page: look through the other pages, ending back on this one.
        let Some(page_count) = self.doc.as_ref().map(|d| d.pages.len()) else { return };
        let start = self.page;
        let matches = self.find.matcher();
        for step in 1..=page_count {
            let p = if forward { (start + step) % page_count } else { (start + page_count - step) % page_count };
            if p != start {
                let doc = self.doc.as_ref().expect("checked above");
                if !scene::page_has_text(doc, p, &matches) {
                    continue;
                }
                self.set_page(p);
            }
            self.find.refresh(self.scene.as_ref(), self.scene_gen);
            let n = self.find.matches.len();
            if n == 0 {
                continue;
            }
            self.find.current = Some(if forward { 0 } else { n - 1 });
            self.focus_item = self.find.current_item();
            let wrapped = if forward { p <= start } else { p >= start };
            if wrapped && n == 1 && p == start {
                self.find.message = Some("only match".into());
            } else if wrapped {
                self.find.message = Some(if forward { "wrapped to the start" } else { "wrapped to the end" }.into());
            }
            return;
        }
    }

    /// Bring a text item into view, zooming in until its text is readable.
    fn focus(&mut self, item: usize, rect: Rect) {
        let Some(scene) = &self.scene else { return };
        let Some(ItemKind::Text(text)) = scene.items.get(item).map(|i| &i.kind) else { return };
        let size = text.runs.iter().map(|r| r.size).fold(0.0, f32::max).max(0.01);
        let mut zoom = self.zoom;
        if size * zoom < 12.0 {
            zoom = 16.0 / size;
        }
        // Don't zoom in so far that the text block overflows the window.
        let extent = text.width.max(text.height);
        if extent * zoom > rect.width() * 0.9 {
            zoom = (rect.width() * 0.9 / extent).max(12.0 / size).min(zoom);
        }
        self.zoom = zoom.clamp(MIN_ZOOM, MAX_ZOOM);
        let c = text.center;
        self.pan = rect.size() * 0.5 - Vec2::new(c[0], scene.height - c[1]) * self.zoom;
    }

    fn fit(&mut self, rect: Rect) {
        let Some(scene) = &self.scene else { return };
        let margin = 24.0;
        let avail = (rect.size() - Vec2::splat(margin * 2.0)).max(Vec2::splat(10.0));
        self.zoom = (avail.x / scene.width.max(0.01)).min(avail.y / scene.height.max(0.01)).clamp(MIN_ZOOM, MAX_ZOOM);
        let page = Vec2::new(scene.width, scene.height) * self.zoom;
        self.pan = (rect.size() - page) * 0.5;
    }

    /// The scrollable range along one axis, or `None` when the page fits and
    /// there is nothing to scroll. The page can be scrolled a quarter of the
    /// window past each edge.
    fn extent(&self, rect: Rect, horizontal: bool) -> Option<Extent> {
        let scene = self.scene.as_ref()?;
        let (page, pan, view) = if horizontal {
            (scene.width * self.zoom, self.pan.x, rect.width())
        } else {
            (scene.height * self.zoom, self.pan.y, rect.height())
        };
        if page + 48.0 <= view {
            return None;
        }
        let margin = view * 0.25;
        Some(Extent { start: pan - margin, total: page + 2.0 * margin, view })
    }

    /// Scroll by `delta` points (positive moves the drawing right/down), staying
    /// within the scrollable range. Axes where the page fits don't scroll.
    fn scroll_by(&mut self, delta: Vec2) {
        let rect = self.canvas_rect;
        for (horizontal, d) in [(true, delta.x), (false, delta.y)] {
            if d == 0.0 {
                continue;
            }
            let Some(extent) = self.extent(rect, horizontal) else { continue };
            let pan = if horizontal { &mut self.pan.x } else { &mut self.pan.y };
            let (lo, hi) = extent.pan_limits(*pan);
            // Never jump back into range: a drag may have left the view outside it.
            *pan = if d > 0.0 { (*pan + d).min(hi.max(*pan)) } else { (*pan + d).max(lo.min(*pan)) };
        }
    }

    /// Overlay scroll bars along the right and bottom edges of the canvas.
    fn scroll_bars(&mut self, ui: &mut egui::Ui, rect: Rect) {
        let vertical = self.extent(rect, false);
        let horizontal = self.extent(rect, true);
        for (is_horizontal, extent) in [(false, vertical), (true, horizontal)] {
            let Some(extent) = extent else { continue };
            // Leave room for the other bar in the corner.
            let corner = if (if is_horizontal { vertical } else { horizontal }).is_some() { SCROLLBAR + 2.0 } else { 0.0 };
            let track = if is_horizontal {
                Rect::from_min_max(
                    Pos2::new(rect.min.x + 2.0, rect.max.y - SCROLLBAR - 2.0),
                    Pos2::new(rect.max.x - 2.0 - corner, rect.max.y - 2.0),
                )
            } else {
                Rect::from_min_max(
                    Pos2::new(rect.max.x - SCROLLBAR - 2.0, rect.min.y + 2.0),
                    Pos2::new(rect.max.x - 2.0, rect.max.y - 2.0 - corner),
                )
            };
            let along = |v: Vec2| if is_horizontal { v.x } else { v.y };
            let length = along(track.size());
            let thumb_len = (extent.view / extent.total * length).clamp(24.0_f32.min(length), length);
            let travel = length - thumb_len;
            let scrolled = (-extent.start / (extent.total - extent.view)).clamp(0.0, 1.0);
            let thumb_start = scrolled * travel;
            let thumb = if is_horizontal {
                Rect::from_min_size(track.min + Vec2::new(thumb_start, 0.0), Vec2::new(thumb_len, SCROLLBAR))
            } else {
                Rect::from_min_size(track.min + Vec2::new(0.0, thumb_start), Vec2::new(SCROLLBAR, thumb_len))
            };

            let id = ui.id().with(("scrollbar", is_horizontal));
            let track_response = ui.interact(track, id.with("track"), Sense::click());
            let thumb_response = ui.interact(thumb, id.with("thumb"), Sense::drag());
            let axis = |d: f32| if is_horizontal { Vec2::new(d, 0.0) } else { Vec2::new(0.0, d) };
            if thumb_response.dragged() && travel > 0.0 {
                // Move the drawing so the thumb follows the pointer.
                let d = along(thumb_response.drag_delta()) * (extent.total - extent.view) / travel;
                self.scroll_by(axis(-d));
            } else if track_response.clicked() {
                // Clicking the track pages towards the click, like other apps.
                if let Some(p) = track_response.interact_pointer_pos() {
                    let before = along(p.to_vec2() - thumb.min.to_vec2()) < 0.0;
                    let page = extent.view * 0.9;
                    self.scroll_by(axis(if before { page } else { -page }));
                }
            }

            let visuals = ui.visuals();
            let track_color = if visuals.dark_mode { Color32::from_white_alpha(18) } else { Color32::from_black_alpha(22) };
            let thumb_color = if thumb_response.dragged() {
                visuals.widgets.active.bg_fill
            } else if thumb_response.hovered() {
                visuals.widgets.hovered.bg_fill
            } else if visuals.dark_mode {
                Color32::from_gray(110)
            } else {
                Color32::from_gray(140)
            };
            let painter = ui.painter();
            painter.rect_filled(track, SCROLLBAR * 0.5, track_color);
            painter.rect_filled(thumb.shrink(1.0), SCROLLBAR * 0.5, thumb_color);
        }
    }

    /// Zoom by `factor`, keeping the paper point under `anchor` fixed.
    fn zoom_about(&mut self, factor: f32, anchor: Pos2, rect: Rect) {
        let new_zoom = (self.zoom * factor).clamp(MIN_ZOOM, MAX_ZOOM);
        let k = new_zoom / self.zoom;
        let a = anchor - rect.min;
        self.pan = a - (a - self.pan) * k;
        self.zoom = new_zoom;
    }

    fn handle_input(&mut self, ctx: &egui::Context) {
        let dropped: Vec<PathBuf> = ctx.input(|i| i.raw.dropped_files.iter().map(|f| f.path().to_path_buf()).collect());
        if let Some(path) = dropped.first() {
            self.open(ctx, path);
        }

        // Find shortcuts work even while the query field has focus.
        let (find, find_next, find_prev, escape) = ctx.input(|i| {
            let f3 = i.key_pressed(Key::F3);
            (i.modifiers.command && i.key_pressed(Key::F), f3 && !i.modifiers.shift, f3 && i.modifiers.shift, i.key_pressed(Key::Escape))
        });
        if find && self.scene.is_some() {
            self.find.open = true;
            self.find.focus = true;
        }
        if find_next || find_prev {
            if self.find.is_active() {
                self.find_step(find_next);
            } else if self.scene.is_some() {
                self.find.open = true;
                self.find.focus = true;
            }
        }
        if escape && self.show_notices {
            self.show_notices = false;
        } else if escape && self.show_about {
            self.show_about = false;
        } else if escape && self.find.open {
            self.find.open = false;
        }

        if ctx.egui_wants_keyboard_input() {
            return;
        }
        // Arrow keys scroll a little; with Shift, by most of a window.
        let arrows = ctx.input(|i| {
            let step = if i.modifiers.shift { 0.9 } else { 0.1 };
            let mut d = Vec2::ZERO;
            if i.key_pressed(Key::ArrowLeft) { d.x += 1.0 }
            if i.key_pressed(Key::ArrowRight) { d.x -= 1.0 }
            if i.key_pressed(Key::ArrowUp) { d.y += 1.0 }
            if i.key_pressed(Key::ArrowDown) { d.y -= 1.0 }
            d * step
        });
        if arrows != Vec2::ZERO {
            let size = self.canvas_rect.size();
            self.scroll_by(Vec2::new(arrows.x * size.x, arrows.y * size.y));
        }

        let (open, next, prev, fit, zoom_in, zoom_out, actual) = ctx.input(|i| {
            let cmd = i.modifiers.command;
            (
                cmd && i.key_pressed(Key::O),
                i.key_pressed(Key::PageDown),
                i.key_pressed(Key::PageUp),
                !cmd && (i.key_pressed(Key::F) || i.key_pressed(Key::Num0)),
                i.key_pressed(Key::Plus) || i.key_pressed(Key::Equals),
                i.key_pressed(Key::Minus),
                !cmd && i.key_pressed(Key::Num1),
            )
        });
        if open {
            self.open_dialog(ctx);
        }
        if next {
            self.set_page(self.page.saturating_add(1));
        }
        if prev {
            self.set_page(self.page.saturating_sub(1));
        }
        if fit {
            self.fit_pending = true;
        }
        let center = ctx.content_rect().center();
        let rect = ctx.content_rect();
        if zoom_in {
            self.zoom_about(1.25, center, rect);
        }
        if zoom_out {
            self.zoom_about(0.8, center, rect);
        }
        if actual {
            self.zoom_about(POINTS_PER_INCH / self.zoom, center, rect);
        }
    }

    fn toolbar(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            self.toolbar_buttons(ui);
            ui.with_layout(egui::Layout::right_to_left(Align::Center), |ui| {
                if ui.button("About").clicked() {
                    self.show_about = true;
                }
            });
        });
    }

    fn toolbar_buttons(&mut self, ui: &mut egui::Ui) {
        if ui.button("Open…").on_hover_text("Open a Visio drawing (Ctrl+O)").clicked() {
            let ctx = ui.ctx().clone();
            self.open_dialog(&ctx);
        }
        let Some(doc) = &self.doc else { return };
        ui.separator();

        let count = doc.pages.len();
        let mut target = self.page;
        if ui.add_enabled(self.page > 0, egui::Button::new("◀")).on_hover_text("Previous page (Page Up)").clicked() {
            target = self.page - 1;
        }
        egui::ComboBox::from_id_salt("page")
            .selected_text(&doc.pages[self.page].name)
            .width(160.0)
            .show_ui(ui, |ui| {
                for (i, page) in doc.pages.iter().enumerate() {
                    ui.selectable_value(&mut target, i, page_label(page));
                }
            });
        if ui.add_enabled(self.page + 1 < count, egui::Button::new("▶")).on_hover_text("Next page (Page Down)").clicked() {
            target = self.page + 1;
        }
        ui.label(format!("{} of {count}", self.page + 1));
        if target != self.page {
            self.set_page(target);
        }

        ui.separator();
        let rect = ui.ctx().content_rect();
        if ui.button("−").on_hover_text("Zoom out (-)").clicked() {
            self.zoom_about(0.8, rect.center(), rect);
        }
        ui.label(format!("{:.0}%", self.zoom / POINTS_PER_INCH * 100.0));
        if ui.button("+").on_hover_text("Zoom in (+)").clicked() {
            self.zoom_about(1.25, rect.center(), rect);
        }
        if ui.button("Fit").on_hover_text("Fit page to window (F, or double-click)").clicked() {
            self.fit_pending = true;
        }
        if ui.button("100%").on_hover_text("Actual size (1)").clicked() {
            self.zoom_about(POINTS_PER_INCH / self.zoom, rect.center(), rect);
        }
        ui.separator();
        ui.toggle_value(&mut self.show_pages, "Pages");
        if ui.toggle_value(&mut self.find.open, "Find").on_hover_text("Find text (Ctrl+F)").clicked() && self.find.open {
            self.find.focus = true;
        }
    }

    fn about_window(&mut self, ctx: &egui::Context) {
        if !self.show_about {
            return;
        }
        let mut open = true;
        egui::Window::new("About Vera View")
            .collapsible(false)
            .resizable(false)
            .anchor(egui::Align2::CENTER_CENTER, Vec2::ZERO)
            .open(&mut open)
            .show(ctx, |ui| {
                ui.set_max_width(420.0);
                ui.horizontal(|ui| {
                    ui.add(egui::Image::new((self.about_icon.id(), Vec2::splat(64.0))));
                    ui.vertical(|ui| {
                        ui.heading("Vera View");
                        ui.label(format!("Version {}", env!("CARGO_PKG_VERSION")));
                        ui.label("A read-only viewer for Microsoft® Visio® drawings (.vsdx, .vsdm, .vstx, .vstm).");
                    });
                });
                ui.separator();
                ui.label(TRADEMARK_NOTICE);
                ui.label(INDEPENDENCE_NOTICE);
                ui.separator();
                ui.label("Built with Rust and open-source libraries including egui, eframe, lyon, roxmltree, zip and image.");
                if ui.link("Third-party notices…").clicked() {
                    self.show_notices = true;
                }
                ui.add_space(6.0);
                ui.vertical_centered(|ui| {
                    if ui.button("  OK  ").clicked() {
                        self.show_about = false;
                    }
                });
            });
        if !open {
            self.show_about = false;
        }
    }

    fn notices_window(&mut self, ctx: &egui::Context) {
        if !self.show_notices {
            return;
        }
        let mut open = true;
        egui::Window::new("Third-party notices")
            .open(&mut open)
            .default_size([720.0, 520.0])
            .pivot(egui::Align2::CENTER_CENTER)
            .default_pos(ctx.content_rect().center())
            .resizable(true)
            .collapsible(false)
            .show(ctx, |ui| {
                let row_height = ui.text_style_height(&egui::TextStyle::Monospace);
                let lines: Vec<&str> = THIRD_PARTY_NOTICES.lines().collect();
                // Only lay out the visible lines; the notices run to thousands.
                egui::ScrollArea::both().auto_shrink(false).show_rows(ui, row_height, lines.len(), |ui, range| {
                    for line in &lines[range] {
                        ui.add(egui::Label::new(egui::RichText::new(*line).monospace()).extend());
                    }
                });
            });
        if !open {
            self.show_notices = false;
        }
    }

    fn find_bar(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.label("Find:");
            let field = ui.add(
                egui::TextEdit::singleline(&mut self.find.query)
                    .desired_width(260.0)
                    .hint_text("Text in shapes"),
            );
            if std::mem::take(&mut self.find.focus) {
                field.request_focus();
            }
            if field.changed() {
                // Search as you type, starting from the top of the current page.
                self.find.current = None;
                self.find_step(true);
            }
            if field.lost_focus() && ui.input(|i| i.key_pressed(Key::Enter)) {
                let shift = ui.input(|i| i.modifiers.shift);
                self.find_step(!shift);
                field.request_focus();
            }
            let active = self.find.is_active();
            if ui.add_enabled(active, egui::Button::new("Previous")).on_hover_text("Previous match (Shift+F3, Shift+Enter)").clicked() {
                self.find_step(false);
            }
            if ui.add_enabled(active, egui::Button::new("Next")).on_hover_text("Next match (F3, Enter)").clicked() {
                self.find_step(true);
            }
            if ui.checkbox(&mut self.find.match_case, "Match case").changed() {
                self.find.current = None;
                self.find_step(true);
            }
            ui.label(self.find.status());
            ui.with_layout(egui::Layout::right_to_left(Align::Center), |ui| {
                if ui.button("×").on_hover_text("Close (Esc)").clicked() {
                    self.find.open = false;
                }
            });
        });
    }

    fn status_bar(&self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            if let Some(path) = &self.path {
                ui.label(path.display().to_string());
            } else {
                ui.label("No file open");
            }
            if let Some(scene) = &self.scene {
                ui.separator();
                ui.label(format!("{:.2} × {:.2} in", scene.width, scene.height));
                ui.separator();
                ui.label(format!("{} shapes", scene.shape_count));
                if !scene.warnings.is_empty() {
                    ui.separator();
                    let notes: Vec<&str> = scene.warnings.iter().map(String::as_str).collect();
                    ui.label(format!("{} rendering notes", notes.len())).on_hover_text(notes.join("\n"));
                }
            }
        });
    }

    fn page_list(&mut self, ui: &mut egui::Ui) {
        let Some(doc) = &self.doc else { return };
        let mut target = self.page;
        egui::ScrollArea::vertical().show(ui, |ui| {
            for (i, page) in doc.pages.iter().enumerate() {
                if ui.selectable_label(i == self.page, page_label(page)).clicked() {
                    target = i;
                }
            }
        });
        self.set_page(target);
    }

    fn canvas(&mut self, ui: &mut egui::Ui) {
        let (rect, response) = ui.allocate_exact_size(ui.available_size(), Sense::click_and_drag());
        self.canvas_rect = rect;
        let painter = ui.painter_at(rect);
        painter.rect_filled(rect, 0.0, canvas_color(ui));

        if let Some((path, _)) = &self.loading {
            let name = path.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default();
            let spinner = Rect::from_center_size(rect.center() - Vec2::new(0.0, 28.0), Vec2::splat(24.0));
            ui.put(spinner, egui::Spinner::new().size(24.0));
            painter.text(rect.center() + Vec2::new(0.0, 8.0), egui::Align2::CENTER_CENTER, format!("Loading {name}…"), FontId::proportional(16.0), ui.visuals().text_color());
            return;
        }
        if self.scene.is_none() {
            let (text, color) = match &self.error {
                Some(err) => (err.clone(), Color32::from_rgb(220, 80, 80)),
                None => (
                    "Open a Visio drawing (.vsdx) with Open… or Ctrl+O,\nor drag a file onto this window.".to_string(),
                    ui.visuals().weak_text_color(),
                ),
            };
            painter.text(rect.center(), egui::Align2::CENTER_CENTER, text, FontId::proportional(16.0), color);
            painter.text(
                rect.center_bottom() - Vec2::new(0.0, 12.0),
                egui::Align2::CENTER_BOTTOM,
                TRADEMARK_NOTICE,
                FontId::proportional(11.0),
                ui.visuals().weak_text_color(),
            );
            return;
        }
        if self.fit_pending {
            self.fit(rect);
            self.fit_pending = false;
            if let (Some([x, y, pct]), Some(scene)) = (self.initial_view.take(), &self.scene) {
                self.zoom = (pct / 100.0 * POINTS_PER_INCH).clamp(MIN_ZOOM, MAX_ZOOM);
                self.pan = rect.size() * 0.5 - Vec2::new(x, scene.height - y) * self.zoom;
            }
        }
        if let Some(item) = self.focus_item.take() {
            self.focus(item, rect);
        }

        if response.dragged() {
            self.pan += response.drag_delta();
        }
        if response.double_clicked() {
            self.fit(rect);
        }
        // Wheel scrolls (Shift+wheel sideways); Ctrl+wheel and pinch zoom. egui
        // reports Ctrl+wheel as zoom and Shift+wheel as horizontal scrolling.
        // Check the rect, not `response`, so the wheel also works over the scroll bars.
        if ui.rect_contains_pointer(rect) {
            let (scroll, zoom, pointer) = ui.input(|i| (i.smooth_scroll_delta, i.zoom_delta(), i.pointer.hover_pos()));
            if (zoom - 1.0).abs() > 1e-4 {
                self.zoom_about(zoom, pointer.unwrap_or(rect.center()), rect);
            }
            if scroll != Vec2::ZERO {
                self.scroll_by(scroll);
            }
        }
        if response.dragged() {
            ui.ctx().set_cursor_icon(egui::CursorIcon::Grabbing);
        }

        let Some(scene) = &self.scene else { return };
        let z = self.zoom;
        let origin = rect.min + self.pan;
        let page_h = scene.height;
        let to_screen = |p: [f32; 2]| Pos2::new(origin.x + p[0] * z, origin.y + (page_h - p[1]) * z);

        let page_rect = Rect::from_min_size(origin, Vec2::new(scene.width, scene.height) * z);
        painter.rect_filled(page_rect.translate(Vec2::splat(3.0)), 0.0, Color32::from_black_alpha(60));
        painter.rect_filled(page_rect, 0.0, Color32::WHITE);

        // Visible area in paper coordinates, for culling.
        let view = [
            (rect.min.x - origin.x) / z,
            page_h - (rect.max.y - origin.y) / z,
            (rect.max.x - origin.x) / z,
            page_h - (rect.min.y - origin.y) / z,
        ];

        let started = Instant::now();
        let find_active = self.find.is_active();
        let current_match = self.find.current_item();
        for (index, item) in scene.items.iter().enumerate() {
            let b = item.bbox;
            if b[2] < view[0] || b[0] > view[2] || b[3] < view[1] || b[1] > view[3] {
                continue;
            }
            // Level of detail: skip anything smaller than half a point on screen.
            // (Text has its own size check.)
            if !matches!(item.kind, ItemKind::Text(_)) && (b[2] - b[0]).max(b[3] - b[1]) * z < 0.5 {
                continue;
            }
            match &item.kind {
                ItemKind::Fill { verts, indices, color } => {
                    let mesh = Mesh {
                        indices: indices.clone(),
                        vertices: verts
                            .iter()
                            .map(|&v| epaint::Vertex { pos: to_screen(v), uv: epaint::WHITE_UV, color: *color })
                            .collect(),
                        ..Default::default()
                    };
                    painter.add(Shape::mesh(mesh));
                }
                ItemKind::Stroke { pts, closed, width, color, pattern } => {
                    let px = (width * z).max(0.75);
                    let stroke = Stroke::new(px, *color);
                    let mut points: Vec<Pos2> = pts.iter().map(|&p| to_screen(p)).collect();
                    points.dedup_by(|a, b| a.distance_sq(*b) < 0.01);
                    if points.len() < 2 {
                        continue;
                    }
                    if *pattern <= 1 {
                        // epaint mitres closed loops without limit, which spikes on
                        // outlines that double back. Open paths get bevelled corners, so
                        // close the loop by wrapping one segment past the start instead.
                        if *closed {
                            let (p0, p1) = (points[0], points[1]);
                            points.extend([p0, p1]);
                        }
                        painter.add(epaint::PathShape::line(points, stroke));
                    } else {
                        if *closed {
                            points.push(points[0]);
                        }
                        let unit = px.max(1.0);
                        let (dash, gap) = match pattern {
                            3 | 10 | 16 => (unit, unit * 2.0),
                            _ => (unit * 6.0, unit * 3.0),
                        };
                        painter.extend(Shape::dashed_line(&points, stroke, dash, gap));
                    }
                }
                ItemKind::Polygon { pts, color } => {
                    let points = pts.iter().map(|&p| to_screen(p)).collect();
                    painter.add(Shape::convex_polygon(points, *color, Stroke::NONE));
                }
                ItemKind::Text(text) => {
                    let center = to_screen(text.center);
                    let quad = draw_text(&painter, text, center, z);
                    if find_active && self.find.is_match(index) {
                        draw_highlight(&painter, quad, center, current_match == Some(index));
                    }
                }
                ItemKind::Image { part, quad } => {
                    let texture = self.textures.entry(part.clone()).or_insert_with(|| {
                        self.doc.as_ref().and_then(|doc| load_texture(ui.ctx(), doc, part))
                    });
                    let corners = quad.map(to_screen);
                    match texture {
                        Some(tex) => {
                            let mut mesh = Mesh::with_texture(tex.id());
                            let uvs = [Pos2::new(0.0, 0.0), Pos2::new(1.0, 0.0), Pos2::new(1.0, 1.0), Pos2::new(0.0, 1.0)];
                            for (pos, uv) in corners.into_iter().zip(uvs) {
                                mesh.vertices.push(epaint::Vertex { pos, uv, color: Color32::WHITE });
                            }
                            mesh.indices = vec![0, 1, 2, 0, 2, 3];
                            painter.add(Shape::mesh(mesh));
                        }
                        None => draw_placeholder(&painter, corners, "image"),
                    }
                }
                ItemKind::Placeholder { quad, label } => draw_placeholder(&painter, quad.map(to_screen), label),
            }
        }
        self.draw_ms = started.elapsed().as_secs_f32() * 1000.0;
        self.scroll_bars(ui, rect);
    }

    /// Errors opening a second file are shown over the current drawing.
    fn error_window(&mut self, ctx: &egui::Context) {
        if self.scene.is_none() {
            return; // The canvas shows the error instead.
        }
        let Some(error) = self.error.clone() else { return };
        let mut open = true;
        egui::Window::new("Could not open file")
            .collapsible(false)
            .resizable(false)
            .anchor(egui::Align2::CENTER_CENTER, Vec2::ZERO)
            .open(&mut open)
            .show(ctx, |ui| {
                ui.label(error);
                if ui.button("OK").clicked() {
                    self.error = None;
                }
            });
        if !open {
            self.error = None;
        }
    }

    fn screenshot_step(&mut self, ctx: &egui::Context) {
        let Some(out) = self.screenshot.clone() else { return };
        ctx.request_repaint();
        if self.loading.is_some() {
            return;
        }
        self.frames += 1;
        // Wait for window fade-in animations to finish before capturing.
        if self.frames == 30 {
            ctx.send_viewport_cmd(ViewportCommand::Screenshot(egui::UserData::default()));
        }
        let shot = ctx.input(|i| {
            i.raw.events.iter().find_map(|e| match e {
                egui::Event::Screenshot { image, .. } => Some(image.clone()),
                _ => None,
            })
        });
        if let Some(image) = shot {
            let rgba: Vec<u8> = image.pixels.iter().flat_map(|c| c.to_srgba_unmultiplied()).collect();
            let [w, h] = image.size;
            if let Err(e) = image::save_buffer(&out, &rgba, w as u32, h as u32, image::ExtendedColorType::Rgba8) {
                eprintln!("Could not save screenshot: {e}");
            }
            println!("canvas draw time: {:.1} ms", self.draw_ms);
            ctx.send_viewport_cmd(ViewportCommand::Close);
        } else if self.frames > 600 {
            eprintln!("Timed out waiting for a screenshot");
            ctx.send_viewport_cmd(ViewportCommand::Close);
        }
    }
}

impl eframe::App for ViewerApp {
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        let ctx = ui.ctx().clone();
        // Files opened from Finder (double-click, Open With, Dock); the latest one wins.
        #[cfg(target_os = "macos")]
        if let Some(path) = crate::macos::take_opened_files().pop() {
            self.open(&ctx, &path);
        }
        self.poll_loading(&ctx);
        self.handle_input(&ctx);
        self.error_window(&ctx);
        self.about_window(&ctx);
        self.notices_window(&ctx);

        egui::Panel::top("toolbar").show(ui, |ui| {
            ui.add_space(4.0);
            self.toolbar(ui);
            ui.add_space(2.0);
        });
        if self.find.open && self.scene.is_some() {
            egui::Panel::top("find").show(ui, |ui| {
                ui.add_space(2.0);
                self.find_bar(ui);
                ui.add_space(2.0);
            });
        }
        self.find.refresh(self.scene.as_ref(), self.scene_gen);
        egui::Panel::bottom("status").show(ui, |ui| self.status_bar(ui));
        if self.show_pages && self.doc.as_ref().is_some_and(|d| d.pages.len() > 1) {
            egui::Panel::left("pages").resizable(true).default_size(180.0).show(ui, |ui| {
                ui.add_space(4.0);
                ui.strong("Pages");
                ui.separator();
                self.page_list(ui);
            });
        }
        egui::CentralPanel::default()
            .frame(egui::Frame::NONE)
            .show(ui, |ui| self.canvas(ui));

        self.screenshot_step(&ctx);
    }
}

fn page_label(page: &Page) -> String {
    if page.background { format!("{} (background)", page.name) } else { page.name.clone() }
}

fn canvas_color(ui: &egui::Ui) -> Color32 {
    if ui.visuals().dark_mode { Color32::from_gray(48) } else { Color32::from_gray(200) }
}

/// Draw a text block, returning the screen corners of the laid-out text
/// (`None` when it is too small to draw).
fn draw_text(painter: &egui::Painter, text: &TextItem, center: Pos2, z: f32) -> Option<[Pos2; 4]> {
    let largest = text.runs.iter().map(|r| r.size).fold(0.0, f32::max) * z;
    if largest < 1.5 {
        return None; // Too small to read; skip the layout work.
    }
    let mut job = LayoutJob::default();
    for run in &text.runs {
        let px = (run.size * z).clamp(1.0, MAX_FONT_PX);
        let family = FontFamily::Name(if run.bold { "doc-bold" } else { "doc" }.into());
        let line = Stroke::new((px / 14.0).max(0.5), run.color);
        job.append(
            &run.text,
            0.0,
            TextFormat {
                font_id: FontId::new(px, family),
                color: run.color,
                italics: run.italic,
                underline: if run.underline { line } else { Stroke::NONE },
                strikethrough: if run.strike { line } else { Stroke::NONE },
                ..Default::default()
            },
        );
    }
    let [ml, mr, mt, mb] = text.margins.map(|m| m * z);
    let (hw, hh) = (text.width * z * 0.5, text.height * z * 0.5);
    let inner_w = hw * 2.0 - ml - mr;
    // Zero-width text blocks (common on connectors) do not wrap.
    job.wrap.max_width = if inner_w > 2.0 { inner_w } else { f32::INFINITY };
    job.halign = match text.halign {
        0 => Align::LEFT,
        1 => Align::Center,
        _ => Align::RIGHT,
    };
    let (left, right) = if inner_w > 2.0 { (-hw + ml, hw - mr) } else { (0.0, 0.0) };
    let x = match text.halign {
        0 => left,
        1 => (left + right) * 0.5,
        _ => right,
    };
    let galley = painter.layout_job(job);
    let gh = galley.size().y;
    let (top, bottom) = (-hh + mt, hh - mb);
    let y = match text.valign {
        0 => top,
        2 => bottom - gh,
        _ => (top + bottom) * 0.5 - gh * 0.5,
    };
    // Paper angles are counter-clockwise; egui rotates clockwise on screen.
    let rot = -text.angle;
    let (s, c) = rot.sin_cos();
    let rotate = |v: Vec2| Vec2::new(v.x * c - v.y * s, v.x * s + v.y * c);
    let pos = center + rotate(Vec2::new(x, y));
    let r = galley.rect.expand(3.0);
    let quad = [r.left_top(), r.right_top(), r.right_bottom(), r.left_bottom()].map(|p| pos + rotate(p.to_vec2()));
    painter.add(epaint::TextShape::new(pos, galley, Color32::BLACK).with_angle(rot));
    Some(quad)
}

/// Mark a find match: a box around the text, or a dot when the text is too small to draw.
fn draw_highlight(painter: &egui::Painter, quad: Option<[Pos2; 4]>, center: Pos2, current: bool) {
    let (fill, stroke) = if current {
        (Color32::from_rgba_unmultiplied(255, 140, 0, 70), Stroke::new(2.5, Color32::from_rgb(255, 110, 0)))
    } else {
        (Color32::from_rgba_unmultiplied(255, 220, 0, 70), Stroke::new(1.0, Color32::from_rgb(220, 160, 0)))
    };
    match quad {
        Some(quad) => {
            painter.add(Shape::convex_polygon(quad.to_vec(), fill, Stroke::NONE));
            // Wrap past the start so the corners join cleanly (see the stroke drawing).
            painter.add(epaint::PathShape::line(vec![quad[0], quad[1], quad[2], quad[3], quad[0], quad[1]], stroke));
        }
        None => {
            painter.circle(center, if current { 6.0 } else { 3.5 }, stroke.color, Stroke::new(1.0, Color32::WHITE));
        }
    }
}

fn draw_placeholder(painter: &egui::Painter, corners: [Pos2; 4], label: &str) {
    let stroke = Stroke::new(1.0, Color32::from_gray(150));
    painter.add(epaint::PathShape::closed_line(corners.to_vec(), stroke));
    painter.line_segment([corners[0], corners[2]], stroke);
    painter.line_segment([corners[1], corners[3]], stroke);
    let center = corners.iter().fold(Vec2::ZERO, |acc, p| acc + p.to_vec2()) / 4.0;
    painter.text(center.to_pos2(), egui::Align2::CENTER_CENTER, label, FontId::proportional(11.0), Color32::from_gray(110));
}

fn load_texture(ctx: &egui::Context, doc: &Document, part: &str) -> Option<TextureHandle> {
    let bytes = doc.package.get(part)?;
    let img = image::load_from_memory(&bytes).ok()?.to_rgba8();
    let size = [img.width() as usize, img.height() as usize];
    let color = egui::ColorImage::from_rgba_unmultiplied(size, img.as_raw());
    Some(ctx.load_texture(part, color, TextureOptions::LINEAR))
}

/// Register the "doc" and "doc-bold" font families used for drawing text,
/// preferring Calibri (Visio's default) when the system has it, then Carlito, which has
/// the same metrics, so text wraps as it does in Visio.
fn install_fonts(ctx: &egui::Context) {
    let mut dirs: Vec<PathBuf> = std::env::var("WINDIR").map(|w| PathBuf::from(w).join("Fonts")).into_iter().collect();
    dirs.extend(
        [
            // Debian / Ubuntu
            "/usr/share/fonts/truetype/crosextra",
            "/usr/share/fonts/truetype/dejavu",
            "/usr/share/fonts/truetype/liberation",
            "/usr/share/fonts/truetype/liberation2",
            // Fedora
            "/usr/share/fonts/google-carlito-fonts",
            "/usr/share/fonts/dejavu-sans-fonts",
            "/usr/share/fonts/liberation-sans",
            // Arch
            "/usr/share/fonts/TTF",
            "/usr/share/fonts/liberation",
            // macOS (Calibri is present when Microsoft Office is installed)
            "/Library/Fonts",
            "/System/Library/Fonts/Supplemental",
        ]
        .map(PathBuf::from),
    );
    if let Some(home) = std::env::var_os("HOME") {
        dirs.push(PathBuf::from(&home).join("Library/Fonts"));
        dirs.push(PathBuf::from(&home).join(".local/share/fonts"));
    }
    let load = |names: &[&str]| {
        names.iter().find_map(|name| dirs.iter().find_map(|dir| std::fs::read(dir.join(name)).ok()))
    };

    let mut fonts = FontDefinitions::default();
    let fallback = fonts.families.get(&FontFamily::Proportional).cloned().unwrap_or_default();
    let mut regular = fallback.clone();
    let mut bold = fallback;
    if let Some(bytes) = load(&[
        "calibri.ttf",
        "Calibri.ttf",
        "Carlito-Regular.ttf",
        "segoeui.ttf",
        "arial.ttf",
        "Arial.ttf",
        "LiberationSans-Regular.ttf",
        "DejaVuSans.ttf",
    ]) {
        fonts.font_data.insert("doc-regular".into(), Arc::new(FontData::from_owned(bytes)));
        regular.insert(0, "doc-regular".into());
        bold.insert(0, "doc-regular".into());
    }
    if let Some(bytes) = load(&[
        "calibrib.ttf",
        "Calibri Bold.ttf",
        "Carlito-Bold.ttf",
        "segoeuib.ttf",
        "arialbd.ttf",
        "Arial Bold.ttf",
        "LiberationSans-Bold.ttf",
        "DejaVuSans-Bold.ttf",
    ]) {
        fonts.font_data.insert("doc-bold".into(), Arc::new(FontData::from_owned(bytes)));
        bold.insert(0, "doc-bold".into());
    }
    fonts.families.insert(FontFamily::Name("doc".into()), regular);
    fonts.families.insert(FontFamily::Name("doc-bold".into()), bold);
    ctx.set_fonts(fonts);
}
